* lecture 1.3 Examples of what not to do
use verb. instead of noun., noun. can make sentence clunky
* lecture 1.4 Overview, principles of effective writing
** cut unnecessary words and phrases; learn to part with your words
** use the active voice(subject + verb + object)
** write with verbs: use strong verbs, avoid turning verbs into nouns, and don't
   bury the main verb
* lecture 1.5 Cut the clutter
** eliminate negatives
He did not win the match. 
-> He lost the match.
** eliminate there are/there is
The data confirm that there is an association between vegetables and cancer.  
-> The data confirm an association between vegetables and cancer. 

There are many physicists who like to write. 
-> Many physicists like to write. 
** omit needless perpositions
i.e "that" and "on" are often superfluous

They agreed that it was true. 
-> They agreed it was true. 

The meeting happened on Monday.
-> The meeting happened Monday.
* lecture 1.6 Practicing cutting clutter
As we can see from Figure 2, if the return kinetic energy is less than 3.2 U_{p}, there will be two electron trajectories associated with this kinetic energy.

-> Figure 2 shows that a return kinetic energy less than 3.2 U_{p} yields electron trajectories.
* lecture 2.1 Use the active voice
The activation of Ca++ channels is induced by the depletion of endolasmic reticulum Ca++ stores.

->Depleting Ca++ from the endoplasmic reticulum activates Ca++ channels.
* lecture 2.2 Is it really OK to use "We" and "I"
It's OK. See example of recommending active voice in style guideline of Science.

http://www.sciencemag.org/site/feature/contribinfo/prep/res/style.xhtml

Another example in Watson and Crick's 1953 paper in Nature:

"We wish to suggest a structure for the salt of D.N.A. ..."

http://www.exploratorium.edu/origins/coldspring/printit.html
* lecture 2.4 Write with verbs
** use strong verbs
use "to be" verbs purposefully and sparingly.
** don't turn verb into noun
** don't bury the main verb
One study of 930 adults with multiple sclerosis (MS) receiving care in one of two managed care settings or in a fee-for-service setting found that only two-thirds of those needing to contact a neurologist for an MS-related problem in the prior 6 months had done so (Vickrey et al 1999).

-> One study found that, of 930 adults with multiple sclerosis (MS) who were receiving care in one of two managed care settings or in a fee-for-service setting, only two-thirds of those needing to contact a neurologist for an MS-related problem in the prior six months had done so (Vickrey et al 1999).
* lecture 2.5 Practice examples
* lecture 2.6 A few grammar tips
* lecture 3.1 Experiment with punctuation
* lecture 3.2 Practice, colon, and dash
* lecture 3.3 Parallelism
* lecture 3.4 Paragraphs
* lecture 3.5 More paragraph practice
* lecture 3.6 A few more tips
