* lecture 1.3 Examples of what not to do
use verb. instead of noun., noun. can make sentence clunky
* lecture 1.4 Overview, principles of effective writing
** cut unnecessary words and phrases; learn to part with your words
** use the active voice(subject + verb + object)
** write with verbs: use strong verbs, avoid turning verbs into nouns, and don't
   bury the main verb
* lecture 1.5 Cut the clutter
** eliminate negatives
He did not win the match. 
-> He lost the match.
** eliminate there are/there is
The data confirm that there is an association between vegetables and cancer.  
-> The data confirm an association between vegetables and cancer. 

There are many physicists who like to write. 
-> Many physicists like to write. 
** omit needless perpositions
i.e "that" and "on" are often superfluous

They agreed that it was true. 
-> They agreed it was true. 

The meeting happened on Monday.
-> The meeting happened Monday.
* lecture 1.6 Practicing cutting clutter
As we can see from Figure 2, if the return kinetic energy is less than 3.2 U_{p}, there will be two electron trajectories associated with this kinetic energy.

-> Figure 2 shows that a return kinetic energy less than 3.2 U_{p} yields electron trajectories.
* lecture 2.1 Use the active voice
The activation of Ca++ channels is induced by the depletion of endolasmic reticulum Ca++ stores.

->Depleting Ca++ from the endoplasmic reticulum activates Ca++ channels.
* lecture 2.2 Is it really OK to use "We" and "I"
It's OK. See example of recommending active voice in style guideline of Science.

http://www.sciencemag.org/site/feature/contribinfo/prep/res/style.xhtml

Another example in Watson and Crick's 1953 paper in Nature:

"We wish to suggest a structure for the salt of D.N.A. ..."

http://www.exploratorium.edu/origins/coldspring/printit.html
* lecture 2.4 Write with verbs
** use strong verbs
use "to be" verbs purposefully and sparingly.
** don't turn verb into noun
** don't bury the main verb
One study of 930 adults with multiple sclerosis (MS) receiving care in one of two managed care settings or in a fee-for-service setting found that only two-thirds of those needing to contact a neurologist for an MS-related problem in the prior 6 months had done so (Vickrey et al 1999).

-> One study found that, of 930 adults with multiple sclerosis (MS) who were receiving care in one of two managed care settings or in a fee-for-service setting, only two-thirds of those needing to contact a neurologist for an MS-related problem in the prior six months had done so (Vickrey et al 1999).
* lecture 2.5 Practice examples
"The fear expressed by some teachers that students would not learn statistics well if they were permitted to use canned computer programs has not been realized in our experience. A careful monitoring of achievement levels before and after the introduction of computers in the teaching of our course revealed no appreciable change in students' performance."

-> Many teachers feared that the use of canned computer programs would prevent students from learning statistics. We monitored student achievement levels before and after the introduction of computers in our course and found no detriments in performance.

"Review of each center's progress in recruitment is important to ensure that the cost involved in maintaining each center's participation is worthwhile."

-> We should review each center's recruitment progress to make sure its continued participation is cost-effective.

It should be emphasized that these proportions generally are not the result of significant increases in moderate and severe injuries, but in many instances reflect mildly injured persons not being seen at a hospital.

-> Shifting proportions in injury severity may reflect stricter hospital admission criteria rather than true increases in moderate and severe injuries.

Important studies to examine the descriptive epidemiology of autism, including the prevalence and changes in the characteristics of the population over time, have begun.

-> Studies have begun to describe the epidemiology of autism, including recent changes in the disorder's prevalence and characteristics.

There are multiple other mechanisms that are important, but most of them are suspected to only have a small impact or are only important because of impact on one of the three primary mechanisms.

-> Multiple other mechanisms play only a small role or work by impacting one of the three primary mechanisms.

After rejecting paths with poor signal-to-noise ratios, we were left with 678 velocity measurements of waves with 7.5 seconds peroid and 891 measurements of 15 second waves.

-> Rejecting paths with poor signal-to-noise ratios left 678 velocity measurements of 7.5-second waves and 891 of 15-second waves.

It is suspected that the importance of temperature has more to do with impacting rates of other reactions than being a mechanism of disinfection itself since ponds are rarely hot enough for temperature alone to cause disinfection.

-> Ponds are rarely hot enough for temperature alone to cause disinfection; thus, the effect of temperature is likely mediated through its impact on the rates of other reactions. 
* lecture 2.6 A few grammar tips
** "Data are" not "Dota is" 
ex. These data show an unusual trend.
    The data are critical.
** Compared to vs. compared with
compare to = to point out similarities between different things
compare with ** (used more often in science)
= to point out differences between similar things
** That vs. which
"That" is the restrictive (defining) pronoun

"Which" is the nonrestrictive (non-defining) pronoun

key: essential (to the sentence) or not
* lecture 3.1 Experiment with punctuation
* lecture 3.2 Practice, colon, and dash
* lecture 3.3 Parallelism
* lecture 3.4 Paragraphs
* lecture 3.5 More paragraph practice
* lecture 3.6 A few more tips
